### ISSUE TITLE
Will the device continue to get firmware updates once you switch to the private MQTT server config?

### ISSUE THREAD

**Issue by ncd7** [GreyEarl/qingping-air-monitor-mqtt#3]
It seems the company is pushing out a lot of updates (which I generally view as a good things though who knows), curious if I'll continue getting updates once I go through the steps or it will freeze the device.

**Comment by GreyEarl** [comment]
This is an official approach to get the devices communicate on your local network. This will not stop communication to the outside world by default. In other words, you can still receive updates, install them and continue receiving local data.
